CaribesTIC/laravuel-spa

- .idea/.gitignore
- .idea/modules.xml
- .idea/vcs.xml
- .idea/vue-frontend-ts.iml
- package-lock.json
- src/Interfaces/IAuth.ts
- src/Interfaces/Store/IAuthStore.ts
- src/main.ts
- src/models/Http/index.ts
- src/plugins/app.ts
- src/plugins/components.ts
- src/plugins/index.ts
- src/plugins/pinia.ts
- src/plugins/router.ts
- src/services/AuthService.ts
- src/stores/Auth.ts
- src/views/Home/Index.vue
- src/views/Login/Form.vue
- src/views/Login/Index.vue
- src/views/Login/useLogin.ts
- tests/views/login/interactingWithForm.spec.ts
- tsconfig.json
The necessary corrections were made.
For now, this model is pending: https://github.com/CaribesTIC/vue-frontend-ts/tree/main/src/models/Http
Also in test files:
- Cannot find module '@/models/Http/' or its corresponding type declarations.ts(2307)
- Cannot find module '@/services/AuthService' or its corresponding type declarations.ts(2307)
- Cannot find module '@/views/Login/Form.vue' or its corresponding type declarations.ts(2307)
- Cannot find name 'describe'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.ts(2582)
- Cannot find name 'test'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.ts(2582)
- Cannot find name 'it'. Do …
> Fix check typing

- src/components/AppErrorMessage.vue
- src/components/AppInput.vue
- src/composables/useUniqueId.ts
- src/modules/Auth/components/FormLogin.vue
- src/modules/Auth/components/FormUser.vue
- src/plugins/components.ts
- tests/globalComponents.ts
- tests/modules/auth/components/formLoginInteractingWith.spec.ts
- tests/modules/auth/components/formLoginMountedCorrectly.spec.ts
- tests/modules/auth/components/formRegisterInteractingWith.spec.ts
- tests/modules/auth/components/formUserInteractingWith.spec.ts
- tests/modules/auth/components/mockProfileUpdateUser.spec.ts
- tests/modules/auth/components/spyProfileUpdateUser.spec.ts
Added the new AppInput.vue global component in both development and testing.
> feat: Add AppInput

- package-lock.json
- package.json
- src/App.vue
- src/assets/css/app.css
- src/assets/css/forms.css
- src/assets/css/panels.css
- src/assets/css/tables.css
- src/components/AppPageHeader.vue
- src/layouts/DashboardLayout.vue
- src/layouts/Header.vue
- src/layouts/RecursiveMenu/Index.vue
- src/layouts/RecursiveMenu/TreeMenu.vue
- src/layouts/Sidebar.vue
- src/modules/User/views/CreateOrEdit.vue
- src/modules/User/views/Index.vue
- tailwind.config.js
Added daisyui.com plugin along with VueUse to implement Light/Dark.
.
> Feat style

- src/modules/ShopCart/components/AppModalOverlay.vue
> style: Z-index shopcart

- src/modules/Auth/views/Home.vue
- src/modules/Auth/views/Login.vue
- src/modules/Auth/views/Register.vue
style: Improving home, login, and register
> style: Improving home, login, and register

- package-lock.json
- src/composables/useSidebar.ts
- src/layouts/Header.vue
- src/layouts/Sidebar.vue
feat: Ability to hide sidebar menu when screen is wide
> feat: Ability to hide sidebar menu when screen is wide

- .env.example
chore: Add NODE_ENV config variable
> chore: Add NODE_ENV config variable

- src/modules/Client/types/index.ts
- src/modules/Client/views/Index.vue
> fix: Remove field deleted_at

- src/modules/Client/components/Client/FormCreateOrEdit.vue
- src/modules/Client/components/Country/FormCreateOrEdit.vue
- src/modules/Client/composables/Client/useCreateOrEdit.ts
- src/modules/Client/composables/Country/useCreateOrEdit.ts
- src/modules/Client/services/Client.ts
- src/modules/Client/services/Country.ts
- src/modules/Client/views/Client/CreateOrEdit.vue
- src/modules/Client/views/Country/CreateOrEdit.vue
feat: Array of options in select.
> feat: Array of options in select

- src/modules/Client/views/Client/Index.vue
> feat: Add foreign key name

- src/modules/Client/views/Client/Index.vue
> fix: Add foreign key name

- src/components/AppErrorMessage.vue
- src/components/AppSelect.vue
- src/modules/Client/components/Country/FormCreateOrEdit.vue
- src/modules/Client/composables/Client/useCreateOrEdit.ts
- src/modules/Client/composables/Country/useCreateOrEdit.ts
- src/modules/Client/routes/indexCountry.ts
- src/modules/Client/types/Client.ts
- src/modules/Client/types/Country.ts
- src/modules/Client/views/Country/Index.vue
> fix: Set typed

- src/modules/Client/types/Client.ts
- src/modules/Client/types/Country.ts
feat: Add foreignTableName type.
> feat: Add foreignTableName type

- src/components/AppSelect.vue
- src/types/Option.ts
- src/types/RadioOption.ts
> feat: Add @/types/Option

- src/modules/Meeting/components/Meeting/FormAgreement.vue
- src/modules/Meeting/components/Meeting/FormApproach.vue
- src/modules/Meeting/components/Meeting/FormAttende.vue
- src/modules/Meeting/components/Meeting/TabAgreement.vue
- src/modules/Meeting/components/Meeting/TabApproach.vue
- src/modules/Meeting/components/Meeting/TabAttende.vue
- src/modules/Meeting/components/Meeting/TableAgreement.vue
- src/modules/Meeting/components/Meeting/TableApproach.vue
- src/modules/Meeting/components/Meeting/TableAttende.vue
- src/modules/Meeting/composables/Meeting/useFormAgreement.ts
- src/modules/Meeting/composables/Meeting/useFormApproach.ts
- src/modules/Meeting/composables/Meeting/useFormAttende.ts
- src/modules/Meeting/composables/Meeting/useTabAgreement.ts
- src/modules/Meeting/composables/Meeting/useTabApproach.ts
- src/modules/Meeting/composables/Meeting/useTabAttende.ts
- src/modules/Meeting/services/AgreementService.ts
- src/modules/Meeting/services/ApproachService.ts
- src/modules/Meeting/services/AttendeService.ts
feat: Built scaffold to formDetail, useFormDetail and tableDetail.
> feat: Built scaffold to formDetail, useFormDetail and tableDetail

- src/components/AppTextarea.vue
- src/modules/Meeting/components/Meeting/FormMeeting.vue
- src/modules/Meeting/composables/Meeting/useFormMeeting.ts
- src/modules/Meeting/composables/Meeting/useTabMeeting.ts
- src/modules/Meeting/views/Meeting/Index.vue
fix: Countries and People sub-modules.
> fix: Countries and People sub-modules

- src/modules/Meeting/components/Meeting/FormMeeting.vue
- src/modules/Meeting/components/Meeting/TabMeeting.vue
> feat: Edit meeting master

- src/modules/Meeting/components/Meeting/FormAgreement.vue
- src/modules/Meeting/components/Meeting/FormApproach.vue
- src/modules/Meeting/components/Meeting/FormAttende.vue
- src/modules/Meeting/components/Meeting/TabAgreement.vue
- src/modules/Meeting/components/Meeting/TabApproach.vue
- src/modules/Meeting/components/Meeting/TabAttende.vue
- src/modules/Meeting/components/Meeting/TableAgreement.vue
- src/modules/Meeting/components/Meeting/TableApproach.vue
- src/modules/Meeting/components/Meeting/TableAttende.vue
- src/modules/Meeting/composables/Meeting/useTabAgreement.ts
- src/modules/Meeting/composables/Meeting/useTabApproach.ts
- src/modules/Meeting/composables/Meeting/useTabAttende.ts
- src/modules/Meeting/composables/Meeting/useTabMeeting.ts
- src/modules/Meeting/routes/indexMeeting.ts
- src/modules/Meeting/services/Agreement.ts
- src/modules/Meeting/services/Approach.ts
- src/modules/Meeting/services/Attende.ts
- src/modules/Meeting/views/Meeting/Index.vue
> feat: Details of master

- src/modules/Meeting/components/Meeting/FormAgreement.vue
- src/modules/Meeting/components/Meeting/FormApproach.vue
- src/modules/Meeting/components/Meeting/FormAttende.vue
- src/modules/Meeting/components/Meeting/TableAgreement.vue
- src/modules/Meeting/components/Meeting/TableApproach.vue
- src/modules/Meeting/components/Meeting/TableAttende.vue
- src/modules/Meeting/composables/Meeting/useFormAgreement.ts
- src/modules/Meeting/composables/Meeting/useFormApproach.ts
- src/modules/Meeting/composables/Meeting/useFormAttende.ts
- src/modules/Meeting/composables/Meeting/useTabAgreement.ts
- src/modules/Meeting/composables/Meeting/useTabApproach.ts
- src/modules/Meeting/composables/Meeting/useTabAttende.ts
- src/modules/Meeting/composables/Person/useCreateOrEdit.ts
- src/modules/Meeting/services/Agreement.ts
- src/modules/Meeting/services/Approach.ts
- src/modules/Meeting/services/Attende.ts
- src/modules/Meeting/types/Meeting/Agreement.ts
- src/modules/Meeting/types/Meeting/Approach.ts
- src/modules/Meeting/types/Meeting/Attende.ts
- src/modules/Meeting/types/Meeting/index.ts
- src/modules/Meeting/views/Person/Index.vue
feat: Types of details & fix: Other types.
> feat: Types of details & fix: Other types

- src/modules/Meeting/components/Meeting/FormAttende.vue
- src/modules/Meeting/components/Meeting/TableAgreement.vue
- src/modules/Meeting/components/Meeting/TableApproach.vue
- src/modules/Meeting/components/Meeting/TableAttende.vue
- src/modules/Meeting/composables/Meeting/useFormAttende.ts
- src/modules/Meeting/composables/Meeting/useTabAttende.ts
- src/modules/Meeting/types/Meeting/Attende.ts
- src/modules/Meeting/views/Meeting/Tabs.vue
feat: Show tableForeignKeysAssoc in details tables.
> feat: Show tableForeignKeysAssoc in details tables
